### ISSUE TITLE
Incompatible dependencies.

### ISSUE THREAD

**Issue by wedoslaw** [ZurichNLP/coling2018-neural-transition-based-morphology#2]
python 2.7.13 and dynet v2.0.2 is incompatible: 
I received an error message while trying to install dynet.

`pip install -e git://github.com/clab/dynet.git@2.0.2#egg=dynet
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: http://pypi.s/root/pypi/+simple/
Obtaining dynet from git+git://github.com/clab/dynet.git@2.0.2#egg=dynet
  Updating ./venv/src/dynet clone (to revision 2.0.2)
  Running command git fetch -q --tags
  Running command git reset --hard -q 9b50b354c3cb66a4163c879ecaa689741a2a6017
  warning: unable to rmdir external/easyloggingpp: Каталог не пуст
Requirement already satisfied: cython in ./venv/lib/python2.7/site-packages (from dynet) (0.29.13)
Collecting numpy (from dynet)
  Downloading http://pypi.s/root/pypi/%2Bf/f11/331530f0eff69/numpy-1.17.1.zip (6.5MB)
     |████████████████████████████████| 6.5MB 12.4MB/s 
    ERROR: Command errored out with exit status 1:
     command: .../venv/bin/python2.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-NRYvrx/numpy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-NRYvrx/numpy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-NRYvrx/numpy/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-NRYvrx/numpy/setup.py", line 31, in <module>
        raise RuntimeError("Python version >= 3.5 required.")
    RuntimeError: Python version >= 3.5 required.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by simon-clematide** [comment]
The numpy version is probably to recent. Sorry, we did not provide a requirements.txt file for the repository. If you try a numpy version from early 2018 it could work.
